stages:
  setup:
    cmd: ipynb-py-convert CNN.ipynb CNN.py
    deps:
    - CNN.ipyb
    outs:
    - CNN.py
  train:
    cmd: python CNN.py
    deps:
    -CNN.py
    outs:
    - metrics.json:
        cache: false
    - cm.png
