name: CNN
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://iterativeai/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
            pip install -r require.txt
            dvc repro
            echo 'done'
            #git fetch --prune
            #dvc metrics diff --show-md master > report.md
            
            #echo "## confusion matrix" >> report.md
            #cml publish cm.png --md >> report.md
            
            #cml send-comment report.md
