name: CNN
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            /opt/hostedtoolcache/Python/3.10.4/x64/bin/python -m pip install --upgrade pip
            pip install -r require.txt
            dvc repo
            
            git fetch --prune
            dvc metrics diff --show-md master > report.md
            
            echo "## confusion matrix" >> report.md
            cml publish cm.png --md >> report.md
            
            cml send-comment report.md
