name: CNN
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            python -m pip install --upgrade pip
            pip install -r require.txt
            ipynb-py-convert CNN.ipynb CNN.py
            python CNN.py 
            
            #echo "## Metrics"
            cat metrics.txt
            
            echo "## Metrics" >> report.md
            #cat metrics.txt >> report.md
            
            #echo "## CM" >> report.md
            #cml-publish cm.png --md >> report.md
            
            cml-send-comment report.md
