name: push-master
on:
  push:
    branches: main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update json
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pip install -r require.txt
            ipynb-py-convert CNN.ipynb CNN.py
            python CNN.py 
            
            git add metrics.json
