name: push-master
on:
  push:
    branches: main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: update json
        run: |
            pip install -r require.txt
            ipynb-py-convert CNN.ipynb CNN.py
            python CNN.py 
            git add metrics.txt
            git add metrics.json
